---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
clickhouse_database_name: logs
clickhouse_create_table: | 
  CREATE TABLE
  log (
      file String, 
      host String, 
      message String, 
      timestamp DateTime64 
      )
  ENGINE=Log;
