---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 
  - src: git@github.com:kmv879/vector-role.git
    scm: git
    version: "1.0"
    name: vector-role 
  - src: git@github.com:kmv879/lighthouse-role.git
    scm: git
    version: "1.0"
    name: lighthouse-role 
