apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
    - name: mtools
      port: 9002
      targetPort: 8080
  selector:
    app: demo
